### ISSUE TITLE
对rocketmq的版本是否有要求

### ISSUE THREAD

**Issue by hbzhu** [hepyu/RocketmqExporter#1]
我们这边rocketmq版本比较老，3.5.8，请问是否支持该版本

**Comment by hepyu** [comment]
我们用的是rocketmq4.3.2版本，没有验证过其他版本；

准确的说应该是依赖rocketmq-console的版本，因为我赶工期，直接调用的rocketmq-console的ajax接口取的聚合数据，要保证rocketmq-console的稳定性，即：
https://github.com/apache/rocketmq-externals/tree/rocketmq-console-1.0.0。

看时间rocketmq-console-1.0.0应该也适配rocketmq3.5.8，所以应该支持。

**Comment by hbzhu** [comment]
测试了是支持的，感谢大佬
