### ISSUE TITLE
请求metrics接口报 invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by ivonlee** [hepyu/RocketmqExporter#2]
![image](https://user-images.githubusercontent.com/1680975/79748470-0ac43d80-8340-11ea-91b2-1eb68b91f6b3.png)
你好，我rocketmq-console 用的1.0版本，请求curl 127.0.0.1:9104/metrics 报上图中的错，怀疑是html没解析成功？

**Comment by hepyu** [comment]
这个需要看一看了，可以提一个PR～
