### ISSUE TITLE
Is there has Grafana Dashboard?

### ISSUE THREAD

**Issue by helloworlde** [hepyu/RocketmqExporter#3]
Would you please provide the Grafana Dashboard also?

**Comment by hepyu** [comment]
here:
https://github.com/hepyu/k8s-app-config/tree/master/product/standard/grafana-prometheus-pro/grafana/provisioning/dashboards/mq-rocketmq

**Comment by helloworlde** [comment]
> here:
> https://github.com/hepyu/k8s-app-config/tree/master/product/standard/grafana-prometheus-pro/grafana/provisioning/dashboards/mq-rocketmq

Got it, thanks!
